patterncoder/bailys

- readme.md
> trying the branch thing

- package.json
- server/views/banquets/venues.jade
venues.jade updated. Here ya go.
> updated venues.jade

- server/views/banquets/venues.jade
> test branching

- server/views/banquets/partyaddons.jade
added first two tables to party add on page
> Party add on table added

- server/controllers/nightclub/bottleServiceController.js
- server/siteSettings.js
- server/views/nightclub/bottleservice.jade
added to bottle service controller and bottle service page.
Had to mess with it a little to get the tables to construct correctly in the bottle services page, depending on if each type of liquor data was an array of liquor objects or a single object.
> bottle service page updated

- package-lock.json
- server/views/banquets/booking.jade
Changed booking info for breakfast, and removed bringing in own wine.
> updated banquets breakfast time, removed bring own wine.

- server/views/about/about.jade
- server/views/banquets/banquetMenusBreakfast.jade
- server/views/banquets/banquetMenusDinner.jade
- server/views/banquets/banquets.jade
- server/views/banquets/booking.jade
- server/views/dining/dining.jade
> Baily.com updates

- server/views/banquets/booking.jade
updated the chart for Room Minimum & Capacity to reflect what is on oldtowndining.
> updates to Room Minimum and Capacity

- server/views/banquets/venues.jade
- server/views/dining/menu.jade
Fixed quite a few grammatical errors within baily.com.
Changed capacity numbers for each room.
> Baily.com update 003

- server/siteSettings.js
- server/views/index.jade
Open table widget is now working, as per Gabe's request.
> Got openTable working for gabe

- server/views/banquets/venues.jade
> updated minimums in venues

- server/includes/layout.jade
- server/includes/navDining.jade
- server/views/index.jade
> Added statement and open table choice award

- public/css/site.css
- server/views/banquets/banquets.jade
- server/views/banquets/venues.jade
- server/views/dining/beer.jade
- server/views/dining/dining.jade
- server/views/dining/menu.jade
- server/views/dining/wine.jade
- server/views/dining/wineByGlass.jade
- server/views/index.jade
- server/views/nightclub/nightclub.jade
Some hover drop-shadows, and 5px radius on some borders.
Added flyers to to dining information.
> minor theme updates

- server/views/dining/dining.jade
- server/views/nightclub/nightclub.jade
flyers now have a dropshadow on hover.
> flyer hover dropshadow

- public/css/site.css
- server/views/index.jade
Logo updated using pure css shadows and effects.
> logo homepage update

- public/css/site.css
Updated the shadow angle for better legibility and professional look.
> updated shadow under home logo

- public/css/site.css
borders were a bit too round, reduced the radius.
> reduced border radius

- public/css/site.css
- public/css/site.styl
- server/views/index.jade
Logo wasn't displaying correctly on mobile devices. Disabling the logo on mobile devices, until a fix can be made.
> had to hide logo on mobile

- server/views/music/booking.jade
- server/views/music/music.jade
The music section needed some help. Added some filler content to make it look finished.
> Added some filler content in the music section

- server/views/index.jade
Updated all of the flyers on baily.com
> upding flyers

- server/views/dining/happyHour.jade
> updated happy hour for august

- server/views/dining/happyHour.jade
Happy Hour set to Monday through Friday 3 to 6pm.
> updated happyhour, and fixed flyers

- server/siteSettings.js
- server/views/nightclub/bottleservice.jade
NYE pricing updated for VIP nightclub menu
> updated proper pricing

- server/views/dining/newYear.jade
Made updates on the new year menu page. Some information is incorrect as it was copied from last year.
> Removed gogo dancers, changed sunday to monday"

- public/js/imageScroll.js
chrome browser on phone had a few issues with display.
> fixed a few bugs on chrome

- public/js/imageScroll.js
- server/views/dining/dining.jade
- server/views/music/music.jade
updated flyers including presidents day
> Valentines

- public/js/imageScroll.js
Image scroller disables the auto-scroll function if a user clicks on one of the buttons.
> image scroll now stops after clicking buttons.

- public/js/imageScroll.js
Now shows back of flyer after a user clicks.
> updated brunch flyer clickable

- public/js/imageScroll.js
- server/views/dining/dining.jade
- server/views/dining/happyHour.jade
- server/views/dining/wineWednesday.jade
- server/views/music/music.jade
- server/views/nightclub/nightclub.jade
totally forgot to push this update.
> removed march flyers

- public/js/banquetSubmit.js
- public/js/ga.js
- public/js/submittr.js
- server/views/banquets/booking.jade
It still needs a few more security updates, but no actual email address is exposed, or passwords.
> Banquet submit

- package.json
azure needs a minimum node version.
> updated minimum node version

- server/routes/banquetSubmit.js
- server/views/banquets/booking.pug
> submission now responds back to the user if it was successful or not

- server/routes/banquetSubmit.js
Azure doesn't support sending emails out of it's system, and only supports sendGrid, which is a paid service, trying to see if an external mailer service (homebrew'd) will work.
> replacing with remote server send method

- server/siteSettings.js
> fixed beers and more incorrect id

- public/js/imageScroll.js
Removed old flyers due to ncovid-19
> removed old flyers
